# Generated by Django 3.1.7 on 2021-05-06 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=11)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('average_interest_rating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('average_quality_rating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('IN', 'initial'), ('RE', 'reported'), ('ON', 'on'), ('OF', 'off')], default='IN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RateVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('interest_rating', models.PositiveSmallIntegerField(choices=[(0, '0/10'), (1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('quality_rating', models.PositiveSmallIntegerField(choices=[(0, '0/10'), (1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_video', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='AbuseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('D', 'dead link'), ('A', 'adult content'), ('V', 'violent content'), ('F', 'false information'), ('O', 'other')], default='D', max_length=1)),
                ('report_dealt_with', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_video', to='videos.video')),
            ],
        ),
    ]
