# Generated by Django 3.1.7 on 2021-04-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('D', 'dead link'), ('A', 'adult content'), ('V', 'violent content'), ('F', 'false information'), ('O', 'other')], default='D', max_length=2)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_video', to='videos.video')),
            ],
        ),
    ]
