# Generated by Django 3.1.7 on 2021-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_abusevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abusevideo',
            name='reason',
            field=models.CharField(choices=[('D', 'dead link'), ('A', 'adult content'), ('V', 'violent content'), ('F', 'false information'), ('O', 'other')], default='D', max_length=1),
        ),
    ]
