# Generated by Django 3.1.7 on 2021-05-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_ratevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratevideo',
            name='average_interest_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='ratevideo',
            name='average_quality_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
