# Generated by Django 3.1.7 on 2021-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20210502_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusevideo',
            name='report_pending',
            field=models.BooleanField(default=True),
        ),
    ]
